### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by icedream** [icedream/go-bsdiff#7]
Add a license compatible with https://github.com/icedream/go-bsdiff/blob/master/bsdiff/LICENSE, maybe just go with the same license.

**Comment by whereswaldon** [comment]
I'd love to be able to use this in some projects, but without a license I can't. If you'd like folks to be able to use your work, we'd appreciate it if you could add a license.

**Comment by icedream** [comment]
I've now licensed it under the 2-clause BSD license (same one as the used bsdiff codebase itself).

**Comment by whereswaldon** [comment]
@icedream That's very generous; thank you for enabling others to use this!
